config/routes.rb
Rails.application.routes.draw do

  resources :notes

  resources :users 
  get 'user/create'

  get 'user/index'

  get 'user/edit'

  resources :tasks
  resources :tickets do
    resources :tasks
  end
  resources :sessions
  put "task_action" => "tickets#task_action", :as => "task_action"
  get "log_out" => "sessions#destroy", :as => "log_out"
  

  root 'tickets#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :ticket
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.status = "assigned"

    #Mail the user with the notification
    TaskMailer.notify(@task).deliver

    respond_to do |format| 
      if @task.save
        format.html { redirect_to edit_ticket_path(@task.ticket), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.jsonTCH/PUT /employees/1
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:user_id, :ticket_id, :status, :notification)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def user_list
    user_list = []
    User.all.each do |user| 
      user_list << [user.netid, user.id]
    end
    user_list
  end
end

app/views/tasks/_form.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">New Task</h4>
      </div>
      <div class="modal-body">

<%= form_for(@task) do |task| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= task.label :user_id %><br>
    <%= task.select :user_id, options_for_select(user_list, @task.user_id) %>
  </div>
  <div class="field">
    <%= task.label :notification %><br>
    <%= task.text_area :notification, rows: 3, cols: 74 %>
  </div>
    <%= task.hidden_field :ticket_id, value: @ticket.id %>
      <div class="modal-footer" style="text-align:left; padding-left:0px">
        <%= task.submit "Submit", class: "btn btn-primary" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="panel panel-default">
<div class="panel-heading">
<h1>Listing tasks</h1>
</div>
<div class="panel-body">
<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Ticket</th>
      <th>Status</th>
      <th>Notification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.user.netid %></td>
        <td><%= task.ticket.id if task.ticket %></td>
        <td><%= task.status %></td>
        <td><%= task.notification %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>

<%= link_to 'New Task', new_task_path, class: "btn btn-primary"  %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @task.user %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= @task.ticket %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Notification:</strong>
  <%= @task.notification %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>