config/routes.rb
Rails.application.routes.draw do

  resources :notes

  resources :users 
  get 'user/create'

  get 'user/index'

  get 'user/edit'

  resources :tasks
  resources :tickets do
    resources :tasks
  end
  resources :sessions
  put "task_action" => "tickets#task_action", :as => "task_action"
  get "log_out" => "sessions#destroy", :as => "log_out"
  

  root 'tickets#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  has_many :notes
  default_scope { order('updated_at DESC') }
  self.per_page = 7
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, except: [:index, :new, :create] 

  # GET /tickets
  # GET /tickets.json
  def index
    @user = User.new unless current_user
    @tickets = Ticket.paginate(page: params[:page])
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to edit_ticket_path(@ticket), notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to edit_ticket_path(@ticket), notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  #DRYer than the old way! 
  def task_action
    action = params[:task_action]
    @task.update status: action 
    respond_to do |format|
      format.html { redirect_to edit_ticket_path(@ticket), notice: "Task #{action}." }
      format.json { head :no_content }
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
      @task = Task.find(params[:task_id]) if params[:task_id]
      @task ||= Task.new
      @tasks = @ticket.tasks
      @note = Note.find(params[:note_id]) if params[:note_id]
      @note ||= Note.new
      @notes = @ticket.notes 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit( :customernetid, :customermavid, :customername, :customerphone, :customeremail, :problem, :category, :resolution, :notes, :user, :page, :description, :task_id, :note_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-primary">
<div class="panel-heading">
<% if @ticket.id %>
<h1>Ticket <%= @ticket.id %> </h1>
<% else %>
<h1>New ticket</h1>
<% end %>
</div>
<div class="panel-body">
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-5 col-md-offset-1"> 
  <div class="field">
    <label> Customer Username</label><br>
    <%= f.text_field :customernetid %>
  </div>
  <div class="field">
    <label> Customer ID Number</label><br>
    <%= f.text_field :customermavid %>
  </div>
  <div class="field">
    <label> Customer Name</label><br>
    <%= f.text_field :customername %>
  </div>
  <div class="field">
    <label> Customer Phone</label><br>
    <%= f.text_field :customerphone %>
  </div>
  <div class="field">
    <label> Customer Email</label><br>
    <%= f.text_field :customeremail %>
  </div>
  <%= f.submit "Save", class: "btn btn-primary" %>
</div>
<div class="col-md-3"> 
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :resolution %><br>
    <%= f.text_area :resolution, rows: 3 %>
  </div>
</div>
<% end %>
</div>
</div>
</div>

app/views/tickets/_links.html.erb
<div class="col-md-12" style="margin-top: 10px; text-align:center">
  <div class="btn-group">
    <a class="btn btn-default" data-toggle="modal" data-target="#noteModal" href="#">Make a Note</a>
    <a class="btn btn-default" data-toggle="modal" data-target="#myModal" href="#">Assign a Task</a>
  </div>
</div>

app/views/tickets/_notes.html.erb
<% unless @ticket.notes.empty? %>
<div class="col-md-6 col-md-offset-3">
<div class="panel panel-primary">
<div class="panel-heading" style="width:100%">
<h3> Notes </h3>
</div>
<div class="panel-body" style="width:100%">
<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Category</th>
      <th>Content</th>
      <th>Created At</th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.user.netid %></td>
        <td><%= note.categorization %></td>
        <td><%= note.content %></td>
        <td><%= note.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
</div>
<% end %>

app/views/tickets/_task_button.html.erb
<% if task.status  == "accepted" %>

<% if task.user == current_user %>

        <!-- Single button -->
        <div class="btn-group">
          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
            Accepted <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Complete", task_action_path(task_id: task.id, id: @ticket.id, task_action: "completed"), method: :put %></li>
            <li class="divider"></li>
            <li><%= link_to "Cancel", task_action_path(task_id: task.id, id: @ticket.id, task_action: "canceled"), method: :put %></li>
          </ul>
        </div>

  <% else %>
        <button class="btn btn-info">
        <%= task.status.titleize %>
        </button>
  <% end %>
<% elsif task.status == "assigned" %>


  <% if task.user == current_user %>

	<!-- Single button -->
	<div class="btn-group">
	  <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
	    Assigned <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu" role="menu">
	    <li><%= link_to "Accept", task_action_path(task_id: task.id, id: @ticket.id, task_action: "accepted"), method: :put %></li>
	    <li class="divider"></li>
	    <li><%= link_to "Cancel", task_action_path(task_id: task.id, id: @ticket.id, task_action: "canceled"), method: :put %></li>
	  </ul>
	</div>

  <% else %>
        <button class="btn btn-warning">
        <%= task.status.titleize %>
        </button>
  <% end %>
<% elsif task.status == "completed" %>
        <button class="btn btn-success">
        <%= task.status.titleize %>
        </button>

<% elsif task.status == "canceled" %>
        <button class="btn btn-danger">
        <%= task.status.titleize %>
        </button>



<% else %>
        <%= task.status %>
<% end %>

app/views/tickets/_tasks.html.erb
<% unless @ticket.tasks.empty? %>
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading" style="width:100%; padding-top:20px">
        <h3> Tasks </h3>
      </div>
      <div class="panel-body" style="width:100%">
        <table class="table">
          <thead>
            <tr>
              <th>User</th>
              <th>Status</th>
              <th>Notification</th>
            </tr>
          </thead>

          <tbody>
            <% @tasks.each do |task| %>
              <tr>
                <td><%= task.user.netid %></td>
                <td><%= render partial: 'task_button', locals: {task: task} %></td>
                <td><%= task.notification %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#ticket" role="tab" data-toggle="tab">Customer Info</a><li>
   <% unless @ticket.tasks.empty? %>
     <li><a href="#tasks" role="tab" data-toggle="tab">Tasks</a><li>
   <% end %>
   <% unless @ticket.notes.empty? %>
     <li><a href="#notes" role="tab" data-toggle="tab">Notes</a><li>
   <% end %>
</ul>

<div class="tab-content" style="padding:20px;">
  <div class="tab-pane fade fade in active" id="ticket">
    <%= render 'form' %>
  </div>
  <div class="tab-pane fade" id="tasks">
    <%= render partial: 'tasks' %>
  </div>
  <div class="tab-pane fade" id="notes">
    <%= render partial: 'notes' %>
  </div>
</div>
<%= render partial: 'tasks/form' %>
<%= render partial: 'notes/form' %>
<%= render partial: 'links' %>

app/views/tickets/index.html.erb
<div class="col-md-6 col-md-offset-3" style="padding-top:15px">
<div class="panel panel-success">

<div class="panel-heading">
<h1>Listing tickets</h1>
</div>

<div class="panel-body">
<table class="table">
  <thead>
    <tr>
      <th>Ticket</th>
      <th>Created By</th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= link_to "#{ticket.id} -- #{ticket.description}", edit_ticket_path(ticket) %></td>
        <td><%= ticket.user.netid if ticket.user%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- <div class="col-md-12"> -->
</div>
<div class="panel-footer" style="text-align:center">
<div class="col-md-12">
<%= will_paginate @tickets, renderer: BootstrapPagination::Rails %>
</div>
<%= link_to 'New Ticket', new_ticket_path, class: "btn btn-primary", style: "color:white" %>
</div>
</div>
</div>

app/views/tickets/new.html.erb
<div class="col-md-12" style="padding:20px">
<%= render 'form' %>
</div>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer Username:</strong>
  <%= @ticket.customernetid %>
</p>

<p>
  <strong>Customer ID Number:</strong>
  <%= @ticket.customermavid %>
</p>

<p>
  <strong>Customer Name:</strong>
  <%= @ticket.customername %>
</p>

<p>
  <strong>Customer Phone Number:</strong>
  <%= @ticket.customerphone %>
</p>

<p>
  <strong>Customeremail:</strong>
  <%= @ticket.customeremail %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @ticket.problem %>
</p>

<p>
  <strong>Category:</strong>
  <%= @ticket.category %>
</p>

<p>
  <strong>Resolution:</strong>
  <%= @ticket.resolution %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @ticket.notes %>
</p>
<% unless @ticket.tasks.empty? %>
<div class="panel panel-primary">
<div class="panel-heading">
<h3> Tasks </h3>
</div>
<div class="panel-body">
<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Status</th>
      <th>Notification</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.user.netid %></td>
        <td><%= task.status %></td>
        <td><%= task.notification %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<% end %>
<%= render partial: 'tasks/form' %>

<%=link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>