config/routes.rb
Rails.application.routes.draw do

  resources :notes

  resources :users 
  get 'user/create'

  get 'user/index'

  get 'user/edit'

  resources :tasks
  resources :tickets do
    resources :tasks
  end
  resources :sessions
  put "task_action" => "tickets#task_action", :as => "task_action"
  get "log_out" => "sessions#destroy", :as => "log_out"
  

  root 'tickets#index'

end

app/views/layouts/_login.html.erb
<% unless current_user %>
<div class="col-md-4 col-md-offset-4">
<div class="panel panel-primary" style="margin-top:10px;">
  <div class="panel-heading" style="text-align:center">
    <h3> Log in </h3>
  </div>
  <div class="panel-body">
    <%= form_tag sessions_path do %>
    <div class="col-md-2 col-md-offset-3" style="text-align:right;"> <!--  margin:auto; max-width:39%"> -->
      <label> Username </label>
      <%= text_field_tag :netid, '', autofocus: "autofocus"%><br />
      <%= label_tag :password %>
      <%= password_field_tag :password %>
      <button class="btn btn-primary" style="margin-top:8px" type="submit">Sign in</button>
     </div>
    <% end %>
  </div>
</div>
</div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissable alert-<%= name.to_s == "notice" ? "success" : "danger" %>" role="alert">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Service Management Pro</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if current_user %>
	  <li><a href="#" style="color:white;"><%= current_user.netid %></a></li>
	  <li><a href="/log_out"><span class="glyphicon glyphicon-eject" style="vertical-align:middle; color:white"></span> Log Out</a></li>
      <% else %>
      <li><a href = "#" data-toggle="modal" data-target="#myModal" style="color:white">Sign Up</a></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Service Management Pro</title>

  <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

    <!-- Latest compiled and minified JavaScript -->
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation'%>
<%= render 'layouts/messages' %>
<%= render 'layouts/login' %>
<%= yield if current_user %>
<%= render 'users/sign_up_form' unless current_user %>
</body>
</html>